image:
  repository: wbuchwalter/kubernetes-acs-engine-autoscaler
  tag: latest
  pullPolicy: Always
rbac:
  install: false
  apiVersion: v1beta1
acsenginecluster:
  resourcegroup: 
  azurespappid: 
  azurespsecret: 
  azuresptenantid: 
  subscriptionid: 
  clientprivatekey: 
  caprivatekey:  

  ## Optional parameter for deployment name if not using default
  #acsdeployment:
  ## Optional parameter for sleep time between scaling loops (default: 60)
  #sleeptime:
  ## Optional parameter for pools to ignore scaling on
  #ignorepools:
  ## Optional parameter denominating number of nodes to spare in a pool after scaling
  #spareagents:
  ## Optional parameter denominating the maximum duration (in seconds) an agent can stay idle before being deleted
  #idlethreshold:
  ## Optional parameter denominating the number of extra agents to create when scaling out
  #overprovision:
